name: Auto approve

on: 
  pull_request_target:
     types:
       - opened
     branches:
       - 'renovate/**' 

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'renovate/**'
    steps:
      - uses: hmarr/auto-approve-action@v3
